# Generated by Django 5.0 on 2023-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wupeiqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dh',
            field=models.CharField(default=None, max_length=32, verbose_name='部门代号'),
        ),
    ]
