# Generated by Django 5.0 on 2023-12-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wupeiqi', '0002_department_dh'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
